### ISSUE TITLE
BE: Add filters to dataset route

### ISSUE THREAD

**Issue by TheAndrewJackson** [ethyca/fides#3519]
# Description
The dataset endpoint needs two new filters for upcoming UI updates

```[tasklist]
### Tasks
- [ ] Add filter that only returns datasets that haven't been linked to any `DatasetConfig` models
- [ ] Add filter that removes all saas template managed datasets
- [ ] Make sure both of these filters can be combined
```

**Comment by Roger-Ethyca** [comment]
moving to done
