### ISSUE TITLE
Review database connectors fields doc

### ISSUE THREAD

**Issue by rsilvery** [ethyca/fides#3737]
This ticket is to update the database connectors so that they match the doc located here: https://ethyca.atlassian.net/wiki/spaces/EN/pages/2707488809/DB+connector+fields

What should be updated:

- [ ] Field order
- [ ] Field labels
- [ ] Required/optional fields
- [ ] Sensitive/not sensitive fields
- [ ] Fields shown/hidden
- [ ] Tooltips
```[tasklist]
### Tasks
```
