### ISSUE TITLE
Integration form fixes

### ISSUE THREAD

**Issue by rsilvery** [ethyca/fides#3815]
Tracking the changes we'll need for connector forms so that we can prioritize and assign them as they come in

```[tasklist]
### Tasks
- [ ] https://github.com/ethyca/fides/issues/3766
- [ ] https://github.com/ethyca/fides/issues/3754
- [ ] https://github.com/ethyca/fides/issues/3763
- [x] Tooltip content is not showing up in connector templates
- [x] DB integration templates: port field default should be set and visible (ex. MariaDB is 3306). It is required but the value has a rational default
- [ ] https://github.com/ethyca/fides/issues/3755
- [x] Fields that require validation like the regulation field on the Adobe Campaign template need to be case insensitive
- [ ] https://github.com/ethyca/fides/issues/3816
- [x] Domo: Set domain default to api.domo.com
- [x] Domo: Add tooltips from https://ethyca.atlassian.net/wiki/spaces/EN/pages/edit-v2/2726133776
- [x] Doordash: change label for signing_secret to `secret'
- [x] Doordash: Figure out what to do with doordash_delivery_hd
- [ ] Doordash: update tooltips https://developer.doordash.com/en-US/api/drive/#tag/Delivery/operation/GetDelivery
- [ ] Fullstory: update tooltips
- [x] Fullstory: Figure out what to do with Fullstory User ID
- [x] Gorgias: update tooltips
- [x] JIRA: add tooltips
- [x] Segment: Change Segment label from `Personas domain` to `Profiles domain`
- [x] Segment: change Segment label from `Namespace ID` to `Space ID`
- [x] Segment: add tooltips
- [x] Wunderkind: add tooltips
- [x] Sentry: add tooltips
- [x] Outreach: add tooltips
- [x] Datadog: add tooltips
- [x] Datadog: change `app key` to `Application Key`
- [x] Rolllbar: add tooitips
- [x] Recharge: add tooltips
- [x] Add Mailchimp tooltips
- [x] Mailchimp transactional: add tooltips
- [x] Hubspot: add tooltips
- [ ] Kustomer: add tooltips
- [x] Salesforce: update tooltips and change label from URI to URL
- [x] Shopify: add tooltips
- [x] Vend: add tooltips
- [x] Vend: update label for access token
- [x] Stripe: update tooltips
```

**Comment by rsilvery** [comment]
Done
